### ISSUE TITLE
Javascript errors when move/copy out

### ISSUE THREAD

**Issue by gapmiss** [1C0D/obsidian-tools#3]
Greetings ~ Testing out your plugin for the copy/move file/folder OUT actions and it's working fine but am getting some javascript errors (opening the file explorer destination).

```
plugin:obsidian-my-tools:2448 Error: Invalid URL
    at openDirectoryInFileManager (plugin:obsidian-my-tools:2446:17)
    at movOpenFileExplorer (plugin:obsidian-my-tools:2607:11)
    at async eval (plugin:obsidian-my-tools:2738:9)
```

Thank you

**Comment by 1C0D** [comment]
version 0.0.1
Ok I put some normalizePath everywhere to not be bothered by paths.
Should be ok

**Comment by gapmiss** [comment]
Still getting the errors after `git pull`  and restart of Obsidian.

I am on `macOS`  the latest `Catalyst` version of Obsidian and here is the debug info.

```
SYSTEM INFO:
	Obsidian version: v1.5.1
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 21.6.0
```

Hope this helps…

**Comment by 1C0D** [comment]
version 1.0.2
yea thks to the precision of your report I could find from where it was coming

**Comment by 1C0D** [comment]
version 1.0.3
ok let's try without any error catch there
```
export async function openDirectoryInFileManager(dirPath: string) {
    let shell = window.electron.remote.shell;
    // try {
        await shell.openExternal(dirPath);
        console.log("we are there")
    // } catch (err) {
    //     console.log("error there")
    //     console.log(err);
    // }
}
```
Maybe it's a stupid error, from the server. So I try to not catch it. (nothing happens)
Do you see the explorer opening at the end with the destination folder ?
Do you see in your obsidian console (ctrl shift i) the "we are there ?
Still an error ?

**Comment by gapmiss** [comment]
No, I do not see a console.log message "we are there"

No, the file explorer does not open at the completion of the move/copy and now the errors are bit more detailed.

```
Uncaught (in promise) Error: Invalid URL
    at /Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:465:71
    at IpcMainImpl.<anonymous> (/Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89772)
    at WebContents.emit (node:events:513:28)
eval	@	move-out-menus.ts:22
await in eval (async)		
e.handleEvent	@	app.js:1
click	@	app.js:1
apply	@	/Applications/Obsidi…acks-registry.js:54
(anonymous)	@	/Applications/Obsidi…derer/remote.js:346
(anonymous)	@	/Applications/Obsidi…derer/remote.js:328
emit	@	node:events:513
onMessage	@	node:electron/js2c/renderer_init:2
```

The errors are referencing "move-out-menus.ts" file at line 22:

```ts
item.onClick(async () => {
  await movOpenFileExplorer(files as (TFile | TFolder)[], "copy");
 });
```

**Comment by 1C0D** [comment]
I will disable this last operation on mac OS. and if I find a solution linked to this error later I will get it back

**Comment by 1C0D** [comment]
hi version 1.0.4 an obsidian dev suggested me another function to do it. 
if it's still not working I will disable this on mac.
Sry I had no activiy last week on this. I was trying to fix another plugin "close similar tabs" and it took me a bunch of time.

**Comment by 1C0D** [comment]
I did a release if you want to use brat

**Comment by gapmiss** [comment]
Excellent! I `git pulled` latest v1.1.0 and the errors are gone and the `Finder` window opens the destination directory.

Thank you for seeing this thru.

**Comment by 1C0D** [comment]
You can thank Liam(obsidian team), he suggested me the answer in another topic...
I added a cool feature, repeat last command. I like it!
