### ISSUE TITLE
[Feature Request] Repeat Lastest Commands - Support for Commands Triggerd from Hotkeys

### ISSUE THREAD

**Issue by FelipeRearden** [1C0D/obsidian-tools#4]
Hello @1C0D !!!!!

First of all, amazing idea!!! I have been looking for a Repeat Lastest Commands for a long time !!!! 

As you know we have three ways of execute commands in Obsidian:

1️⃣ Open Command Palette and Click in the command item
2️⃣ Open Command Palette and press ENTER in the command item
3️⃣ Execute a command from a hotkey using the keyboard

As far as I understood, `My Tools: Repeat Last Command` and `My Tools:  Repeat Last CommandS` are only available when using 1️⃣

My FR is about 3️⃣ I would like to be able to use  `My Tools: Repeat Last Command` and `My Tools:  Repeat Last CommandS` when executing commands from hotkeys. 

Is it possible ??? 🙏 🙏 🙏

<hr>

Thanks for reading this FR!!! 
I wish you a fantastic day ☀️

**Comment by 1C0D** [comment]
wow thks for this nice request. indeed, it was very needed. done

**Comment by FelipeRearden** [comment]
> wow thks for this nice request. indeed, it was very needed. done

Amazing @1C0D !!! 
Working perfect on version 1.3.0 
Thank you very much for the quick reply 😀 

I just wanna ask you one more question: do you have plans of adding this plug-in to the community store ? 

Thanks again 😄

**Comment by 1C0D** [comment]
You mean obsidian-tools or just last command as an independent plugin. I was wondering about this. Sometime this is better to have a plugin doing just one thing. And on the other hand, not doing x plugins for just one thing seems a lack of time. The only thing making trouble, is the fact to import files (a tool that I have to improve...) which is breaking obsidian rules if I remember well what I read in documentation. But at the same time, they are doing importer.

**Comment by FelipeRearden** [comment]
I mean last command as an independent plugin.

I am asking this because it is just a great feature and so useful that as an independent plug-in could gather more attention and be able to help more obsidian users. 

And since it's a plug-in that is already 100% of the scope fulfilled it is less difficult to maintain. 

In my humble opinion, might be a good idea to publish as an independent plug-in 😀

**Comment by 1C0D** [comment]
Thks for your advice,I will do this in the week

**Comment by FelipeRearden** [comment]
> Thks for your advice,I will do this in the week

Thank you very much @1C0D !!!! I wish you a fantastic day ☀️

**Comment by 1C0D** [comment]
ok done. release published

**Comment by FelipeRearden** [comment]
> ok done. release published

Amazing !!!!! Thank you very much @1C0D 🙏
